export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const SET_FILTER = 'FETCH_MOVIES_FAILURE';
//export const SET_TOTAL_MOVIES = 'SET_TOTAL_MOVIES';
//export const SET_TOTAL_PAGES = 'SET_TOTAL_MOVIES';